---
title: "Cascade 1.0: Test All Possible Models"
author: "[John Zobolas](https://github.com/bblodfon)"
date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    css: "../cell-lines-2500/style.css"
    theme: united
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    number_sections: false
    code_folding: hide
    code_download: true
---

```{r Render command, eval=FALSE, include=FALSE}
rmarkdown::render(input = "test.Rmd", output_dir = "docs")
```

```{r}
knitr::opts_chunk$set(cache=TRUE, fig.align = 'center')
```

## Libraries {-}

Loading libraries:
```{r Load libraries, message = FALSE}
library(emba)
library(usefun)
```

## Dataset {-}

We generated all possible boolean models using [abmlog](https://github.com/druglogics/abmlog) by performing **all possible mutations of the link operator**, based on the input  of the Cascade 1.0

Command to run: `java -cp target/abmlog-1.4.0-jar-with-dependencies.jar eu.druglogics.abmlog.BooleanModelGenerator --file=test/network.sif --attractors=fixpoints --parallel`


```{r}
models.dir = paste0(getwd(), "/models")
topology.file = paste0(getwd(), "/topology")

net = construct_network(topology.file, models.dir)
models.link.operator = get_link_operators_from_models_dir(models.dir)
```


